[package]
name = "gene-bank-search-btree"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
btree = { path = "../btree" }
gene = { path = "../gene" }